### ISSUE TITLE
ResNet-50 uses Bottleneck Block

### ISSUE THREAD

**Issue by kilianyp** [switchablenorms/Switchable-Normalization#18]
Hi,
I noticed that your ResNet-50 will not use a Bottleneck, the orignal implementation does however:
https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L231
https://github.com/switchablenorms/Switchable-Normalization/blob/master/face_recognition/models/backbones/resnet.py#L106

Is this on purpose?

**Comment by JiaminRen** [comment]
yes, it is on purpose. This model reference on [insightface](https://github.com/deepinsight/insightface/blob/master/src/symbols/fresnet.py)

**Comment by kilianyp** [comment]
Hi,
thanks for the reference!
